'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Player={id:string;name:string;score:number};type Game={code:string;host:string;players:Player[];phase:string;round:number;total:number;spotlight:string;question:{q:string;a:string[]};answer:number|null;hasAnswered:boolean;guessed:string[];myGuess:number|null;earned:Record<string,number>;winner:string|null;chosen:string|null;miniKind:string|null;miniIndex:number|null;miniDone:boolean};
type Session={code:string;token:string;me:string};
const storeKey='inside-joke-session';
export default function Home(){const [session,setSession]=useState<Session|null>(null),[game,setGame]=useState<Game|null>(null),[name,setName]=useState(''),[roomCode,setRoomCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
const refresh=useCallback(async(s:Session)=>{try{const r=await fetch(`/api/game?code=${encodeURIComponent(s.code)}&token=${encodeURIComponent(s.token)}`,{cache:'no-store'});const d=await r.json() as {game:Game;error?:string};if(r.ok){setGame(d.game);setError('')}else if(r.status===403||r.status===404){setSession(null);setGame(null);localStorage.removeItem(storeKey)}}catch{}},[]);
useEffect(()=>{const saved=localStorage.getItem(storeKey);if(saved){try{const s=JSON.parse(saved) as Session;setSession(s);refresh(s)}catch{localStorage.removeItem(storeKey)}}},[refresh]);
useEffect(()=>{if(!session)return;const timer=setInterval(()=>refresh(session),1500);return()=>clearInterval(timer)},[session,refresh]);
async function act(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{const r=await fetch('/api/game',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,code:session?.code||roomCode.trim().toUpperCase(),token:session?.token,name:name.trim(),...extra})});const d=await r.json() as {game:Game;code:string;token:string;me:string;error?:string};if(!r.ok)throw new Error(d.error||'Please try again');if(action==='create'||action==='join'){const s={code:d.code,token:d.token,me:d.me};setSession(s);localStorage.setItem(storeKey,JSON.stringify(s));history.replaceState(null,'',`/?room=${d.code}`)}setGame(d.game)}catch(e){setError(e instanceof Error?e.message:'Please try again')}finally{setBusy(false)}}
const me=game?.players.find(x=>x.id===session?.me),spot=game?.players.find(x=>x.id===game.spotlight),chosen=game?.players.find(x=>x.id===game.chosen),winner=game?.players.find(x=>x.id===game.winner),isSpot=me?.id===spot?.id,isChosen=me?.id===chosen?.id;
useEffect(()=>{const c=new URLSearchParams(location.search).get('room');if(c)setRoomCode(c.toUpperCase())},[]);
return <div className="shell"><header className="top"><div className="brand"><span className="brandmark">☺</span> Inside Joke</div><span className="pill">2–8 players · Play on your own device</span></header>{!session||!game?<div className="landing"><section className="intro"><div className="eyebrow">The friend test</div><h1>How well do you really know them?</h1><p>Take turns in the spotlight. Guess your friends’ answers, earn points, and play a bonus challenge.</p><div className="intro-meta"><span>2–8 players</span><span>Play on your own device</span></div></section><div className="joinbox"><div className="form-kicker">START PLAYING</div><h2>Create or join a room</h2><label className="field" htmlFor="name">Your name</label><Input id="name" className="input" maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="What should friends call you?"/><label className="field" htmlFor="code">Room code <span className="small">(to join)</span></label><Input id="code" className="input" maxLength={5} value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} placeholder="ABCDE"/><div className="row"><Button className="btn" disabled={busy||!name.trim()} onClick={()=>act('create')}>Create room</Button><Button className="btn alt" disabled={busy||!name.trim()||roomCode.length!==5} onClick={()=>act('join')}>Join room</Button></div>{error&&<p className="error" role="alert">{error}</p>}<p className="hint">The host shares the code. Everyone opens the game on their own phone.</p></div></div>:<><div className="roomhead"><div><div className="eyebrow">Room code</div><div className="code">{game.code}</div></div><Button className="btn ghost" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?room=${game.code}`)}catch{} }}>Copy invite link</Button></div><div className="grid"><main className="panel stage"><div className="status">{game.phase==='lobby'?'Waiting for friends':game.phase==='finished'?'Game over':`Round ${game.round+1} of ${game.total}`}</div>{game.phase!=='lobby'&&game.phase!=='finished'&&<div className="round-meter" role="progressbar" aria-label="Game progress" aria-valuenow={game.round+1} aria-valuemin={1} aria-valuemax={game.total}><span style={{width:`${((game.round+1)/game.total)*100}%`}}/></div>}{game.phase==='lobby'&&<><h1>Gather your people.</h1><p>Share the code <strong>{game.code}</strong>. You need at least two players to begin.</p><div className="notice">{game.players.length} of 8 players joined</div>{session.me===game.host?<Button className="btn" disabled={busy||game.players.length<2} onClick={()=>act('start')}>Start game</Button>:<p>Waiting for the host to start…</p>}</>}
{game.phase==='answer'&&<><p className="eyebrow">{isSpot?'You’re in the spotlight':`${spot?.name} is in the spotlight`}</p><h1>{game.question.q}</h1>{isSpot?<><p>Choose your answer privately. Your friends will try to guess it.</p><div className="options">{game.question.a.map((o,i)=><Button key={i} className="option" disabled={busy} onClick={()=>act('answer',{value:i})}>{o}</Button>)}</div></>:<p>Waiting for {spot?.name} to choose an answer…</p>}</>}
{game.phase==='guess'&&<><p className="eyebrow">Guess time · {spot?.name}</p><h1>{game.question.q}</h1>{isSpot?<p>Your answer is locked. {game.guessed.length} of {game.players.length-1} friends have guessed.</p>:game.myGuess!==null?<div className="notice">Guess locked: <strong>{game.question.a[game.myGuess]}</strong><p>{game.guessed.length} of {game.players.length-1} guesses in.</p></div>:<><p>What did {spot?.name} choose?</p><div className="options">{game.question.a.map((o,i)=><Button key={i} className="option" disabled={busy} onClick={()=>act('guess',{value:i})}>{o}</Button>)}</div></>}</>}
{game.phase==='reveal'&&<><p className="eyebrow">The reveal</p><h1>{spot?.name} chose…</h1><h2 className="winner">{game.question.a[game.answer??0]}</h2><div className="notice">{winner?.name} wins this round. {chosen?.name} gets the next choice.</div><div className="scorelist">{game.players.map(p=><div className="person" key={p.id}>{p.name}<span className="points">+{game.earned[p.id]||0}</span></div>)}</div><Button className="btn" disabled={busy} onClick={()=>act('revealNext')}>Continue</Button></>}
{game.phase==='choice'&&<><p className="eyebrow">Your call, {chosen?.name}</p><h1>Regular round or a bonus challenge?</h1><p>{chosen?.name} was picked at random from the players who did not win the round.</p>{isChosen?<div className="options"><Button className="btn" disabled={busy} onClick={()=>act('choose',{value:'mini'})}>Try a mini-game · win 2 points</Button><Button className="btn alt" disabled={busy} onClick={()=>act('choose',{value:'regular'})}>Continue regular rounds</Button></div>:<p>Waiting for {chosen?.name} to decide…</p>}</>}
{game.phase==='mini'&&<><p className="eyebrow">Bonus challenge · {chosen?.name}</p>{game.miniKind==='puzzle'?<><h1>Quick puzzle</h1><p>What number comes next? 2, 4, 8, 16, …</p>{isChosen&&!game.miniDone?<div className="options">{['18','24','32','64'].map((v,i)=><Button className="option" key={v} disabled={busy} onClick={()=>act('miniAnswer',{value:i})}>{v}</Button>)}</div>:<p>{game.miniDone?'Challenge finished.':'Waiting for an answer…'}</p>}</>:<><h1>Find the hidden star</h1><p>Tap the star hiding among the shapes. Only {chosen?.name} can answer.</p><div className="mini-grid">{Array.from({length:25},(_,i)=><Button key={i} className="tile" disabled={!isChosen||game.miniDone||busy} aria-label={`Tile ${i+1}`} onClick={()=>act('miniAnswer',{value:i})}>{i===game.miniIndex?'✦':['✿','◆','●','✚'][i%4]}</Button>)}</div>{!isChosen&&<p>Follow along while {chosen?.name} searches.</p>}</>}{game.miniDone&&<><div className="notice">Challenge complete. Check the updated scores.</div><Button className="btn" disabled={busy} onClick={()=>act('miniNext')}>Next round</Button></>}</>}
{game.phase==='finished'&&<><p className="eyebrow">Final scores</p><h1>That’s a wrap.</h1><h2 className="winner">{game.players.filter(x=>x.score===Math.max(...game.players.map(p=>p.score))).map(x=>x.name).join(' & ')} {game.players.filter(x=>x.score===Math.max(...game.players.map(p=>p.score))).length===1?'wins!':'tie!'}</h2><p>Everyone had two turns in the spotlight.</p><Button className="btn alt" onClick={()=>{localStorage.removeItem(storeKey);setSession(null);setGame(null);history.replaceState(null,'','/')}}>Start a new room</Button></>}
{error&&<p className="error" role="alert">{error}</p>}</main><aside className="panel scoreboard"><div className="eyebrow">The scoreboard · {game.players.length} {game.players.length===1?'player':'players'}</div><div className="scorelist">{[...game.players].sort((a,b)=>b.score-a.score).map(p=><div className="person" key={p.id}><span className="avatar">{p.name.charAt(0).toUpperCase()}</span><span>{p.name}{p.id===session.me?' (you)':''}</span><span className="points">{p.score}</span></div>)}</div><hr className="divider"/><p className="small">Correct guess: 2 points · Spotlight player: 1 point if at least half guess right · Bonus challenge: 2 points.</p></aside></div></>}</div>}
