import { env } from 'cloudflare:workers';
import { AVATARS, DEFAULT_AVATAR } from '@/lib/avatars';
export const runtime = 'edge';
type Player={id:string;token:string;name:string;score:number;avatar?:string};
type Game={code:string;host:string;players:Player[];phase:'lobby'|'answer'|'guess'|'reveal'|'choice'|'mini'|'finished';round:number;roundsPerPlayer?:number;question:number;answer:number|null;guesses:Record<string,number>;earned:Record<string,number>;winner:string|null;chosen:string|null;miniKind:'puzzle'|'object'|null;miniIndex:number;miniDone:boolean};
const QUESTIONS=[
 {q:'Your dream free Saturday looks like…',a:['A spontaneous road trip','Staying in with a movie','A big meal with friends','Trying a new hobby']},
 {q:'Which superpower would you actually pick?',a:['Teleportation','Reading minds','Stopping time','Talking to animals']},
 {q:'You find a plane ticket to anywhere. Where first?',a:['A tropical beach','A mountain cabin','A bustling city','A place full of history']},
 {q:'Which role would you play in a heist movie?',a:['The mastermind','The smooth talker','The getaway driver','The accidental hero']},
 {q:'What would you bring to a deserted island?',a:['A book collection','A survival kit','My favorite person','A solar-powered phone']},
 {q:'A surprise party for you should include…',a:['Dancing all night','A small dinner','An outdoor adventure','Absolutely no surprise']},
 {q:'Which tiny luxury makes your day?',a:['Coffee in peace','Fresh sheets','A long shower','A snack at midnight']},
 {q:'Your ideal vacation pace?',a:['Every minute planned','Wander and discover','Sleep and recharge','Follow the food']},
 {q:'Which new skill would you learn overnight?',a:['Play an instrument','Speak every language','Cook anything','Dance perfectly']},
 {q:'What would your friends most likely call you about?',a:['Advice','A last-minute plan','A practical fix','A good laugh']},
 {q:'At a party, where would we find you?',a:['Running the music','Deep in conversation','Making everyone laugh','Finding the snacks']},
 {q:'Choose a secret personal theme song vibe.',a:['Epic movie soundtrack','Happy pop anthem','Chill acoustic track','Dramatic rock song']},
];
const uid=()=>crypto.randomUUID();
const code=()=>Array.from(crypto.getRandomValues(new Uint8Array(5))).map(x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%32]).join('');
const db=()=>{if(!env.DB)throw new Error('Room storage unavailable');return env.DB};
const response=(g:Game,id:string)=>({code:g.code,host:g.host,players:g.players.map(({id,name,score,avatar})=>({id,name,score,avatar:avatar??DEFAULT_AVATAR})),phase:g.phase,round:g.round,roundsPerPlayer:g.roundsPerPlayer??2,total:g.players.length*(g.roundsPerPlayer??2),spotlight:g.players[g.round%g.players.length]?.id,question:QUESTIONS[g.question],answer:g.phase==='reveal'||g.phase==='choice'||g.phase==='mini'||g.phase==='finished'?g.answer:null,hasAnswered:g.answer!==null,guessed:Object.keys(g.guesses),myGuess:g.guesses[id]??null,earned:g.earned,winner:g.winner,chosen:g.chosen,miniKind:g.miniKind,miniIndex:g.phase==='mini'&&g.chosen===id?g.miniIndex:null,miniDone:g.miniDone});
const fail=(message:string,status=400)=>Response.json({error:message},{status});
const load=async(c:string)=>{const row=await db().prepare('SELECT state,version FROM rooms WHERE code = ?').bind(c).first<{state:string;version:number}>();return row?{g:JSON.parse(row.state) as Game,version:row.version}:null};
export async function GET(req:Request){try{const u=new URL(req.url),c=(u.searchParams.get('code')||'').toUpperCase(),t=u.searchParams.get('token');const r=await load(c);if(!r)return fail('Room not found',404);const p=r.g.players.find(p=>p.token===t);if(!p)return fail('Your session is no longer in this room',403);return Response.json({game:response(r.g,p.id),me:p.id})}catch(e){console.error(e);return fail('Could not load the room',500)}}
export async function POST(req:Request){try{const b=await req.json() as Record<string,unknown>;const action=String(b.action||'');const name=String(b.name||'').trim().slice(0,24);const avatar=AVATARS.includes(String(b.avatar) as (typeof AVATARS)[number])?String(b.avatar):DEFAULT_AVATAR;if(action==='create'){if(!name)return fail('Enter your name');for(let i=0;i<5;i++){const c=code(),p={id:uid(),token:uid(),name,score:0,avatar};const g:Game={code:c,host:p.id,players:[p],phase:'lobby',round:0,roundsPerPlayer:2,question:0,answer:null,guesses:{},earned:{},winner:null,chosen:null,miniKind:null,miniIndex:0,miniDone:false};try{await db().prepare('INSERT INTO rooms (code,state,version,updated_at) VALUES (?,?,0,?)').bind(c,JSON.stringify(g),Date.now()).run();return Response.json({code:c,token:p.token,me:p.id,game:response(g,p.id)})}catch{continue}}return fail('Could not create a room',500)}
const c=String(b.code||'').toUpperCase().trim(),token=String(b.token||'');for(let retry=0;retry<7;retry++){const row=await load(c);if(!row)return fail('Room not found',404);const g=row.g;let p=g.players.find(p=>p.token===token);if(action==='join'){if(!name)return fail('Enter your name');if(g.phase!=='lobby')return fail('This game has already started');if(g.players.length>=8)return fail('Room is full');if(g.players.some(x=>x.name.toLowerCase()===name.toLowerCase()))return fail('That name is already taken');p={id:uid(),token:uid(),name,score:0,avatar};g.players.push(p)}else{if(!p)return fail('Your session is no longer in this room',403);
const spot=g.players[g.round%g.players.length];
if(action==='setRounds'){if(g.host!==p.id||g.phase!=='lobby')return fail('Only the host can set rounds before the game starts');const v=Number(b.value);if(!Number.isInteger(v)||v<1||v>4)return fail('Choose 1 to 4 rounds per player');g.roundsPerPlayer=v}
else if(action==='start'){if(g.host!==p.id||g.phase!=='lobby')return fail('Only the host can start');if(g.players.length<2)return fail('Invite at least one friend');g.phase='answer'}
else if(action==='answer'){if(g.phase!=='answer'||p.id!==spot.id)return fail('Wait for your spotlight turn');const v=Number(b.value);if(!Number.isInteger(v)||v<0||v>3)return fail('Choose an answer');g.answer=v;g.phase='guess'}
else if(action==='guess'){if(g.phase!=='guess'||p.id===spot.id||g.guesses[p.id]!==undefined)return fail('You cannot guess now');const v=Number(b.value);if(!Number.isInteger(v)||v<0||v>3)return fail('Choose an answer');g.guesses[p.id]=v;if(Object.keys(g.guesses).length===g.players.length-1){for(const player of g.players){const earned=player.id===spot.id?(Object.values(g.guesses).filter(x=>x===g.answer).length>=Math.ceil((g.players.length-1)/2)?1:0):(g.guesses[player.id]===g.answer?2:0);g.earned[player.id]=earned;player.score+=earned}const top=Math.max(...Object.values(g.earned));const tied=g.players.filter(x=>g.earned[x.id]===top);g.winner=tied[Math.floor(Math.random()*tied.length)].id;const eligible=g.players.filter(x=>x.id!==g.winner);g.chosen=eligible[Math.floor(Math.random()*eligible.length)].id;g.phase='reveal'}}
else if(action==='revealNext'){if(g.phase!=='reveal')return fail('Wait for the reveal');g.phase='choice'}
else if(action==='choose'){if(g.phase!=='choice'||p.id!==g.chosen)return fail('It is someone else’s choice');if(b.value==='regular'){next(g)}else if(b.value==='mini'){g.miniKind=Math.random()<.5?'puzzle':'object';g.miniIndex=Math.floor(Math.random()*25);g.miniDone=false;g.phase='mini'}else return fail('Choose a round')}
else if(action==='miniAnswer'){if(g.phase!=='mini'||p.id!==g.chosen||g.miniDone)return fail('Wait for your mini-game');const right=g.miniKind==='puzzle'?Number(b.value)===2:Number(b.value)===g.miniIndex;g.miniDone=true;if(right){p.score+=2;g.earned[p.id]=(g.earned[p.id]||0)+2}}
else if(action==='miniNext'){if(g.phase!=='mini'||!g.miniDone)return fail('Finish the mini-game first');next(g)}
else return fail('Unknown action')}
const updated=await db().prepare('UPDATE rooms SET state=?,version=version+1,updated_at=? WHERE code=? AND version=?').bind(JSON.stringify(g),Date.now(),c,row.version).run();if(updated.meta.changes===1)return Response.json({code:c,token:p?.token,me:p?.id,game:response(g,p!.id)});if(action==='join')return fail('Someone joined at the same time. Try again.')}
return fail('Room is busy, please retry',409)}catch(e){console.error(e);return fail('Something went wrong. Please try again.',500)}}
function next(g:Game){g.round++;if(g.round>=g.players.length*(g.roundsPerPlayer??2)){g.phase='finished';return}g.question=g.round%QUESTIONS.length;g.answer=null;g.guesses={};g.earned={};g.winner=null;g.chosen=null;g.miniKind=null;g.miniDone=false;g.phase='answer'}
